In [2]:
import pandas as pd
import os
import sys
import pymongo

if os.path.abspath('../') not in sys.path:
    sys.path.insert(0, os.path.abspath('../'))

In [3]:
database_username = "admin01"
database_password = "LZRKfNnjX38rCOMs"
database_cluster_name = "bigdataforengineering.wef2a2d.mongodb.net"
connection_string = f"mongodb+srv://{database_username}:{database_password}@{database_cluster_name}/?retryWrites=true&w=majority"

database_name = "environment"
collection_name = "raw_openweather"

client = pymongo.MongoClient(connection_string)

# Check if the connection was successful
if client.server_info():
    print("Connected to MongoDB successfully!")


db = client[database_name]
collection = db[collection_name]
cursor = collection.find({})
data_list = list(cursor)
Vie_weather = pd.DataFrame(data_list)
Vie_weather

Connected to MongoDB successfully!

,_id,temp,temp_min,sunrise,report_time,sunset,description,humidity,location,pressure,feels_like,temp_max,wind
0,659e617af63ecd73f81c1050,305.12,305.12,1704842319,2024-01-10 09:19:37,1704883911,overcast clouds,52.0,Long Xuyen,1007.0,307.95,305.12,1.51
1,659e617af63ecd73f81c104f,303.11,303.11,1704842106,2024-01-10 09:18:06,1704883854,overcast clouds,56.0,Soc Trang,1008.0,305.15,303.11,5.68
2,659e617af63ecd73f81c104c,304.11,304.11,1704842263,2024-01-10 09:13:35,1704884095,overcast clouds,53.0,Ca Mau,1008.0,306.31,304.11,5.06
3,659e617af63ecd73f81c104d,301.75,301.75,1704842135,2024-01-10 09:15:06,1704883947,overcast clouds,64.0,Bac Lieu,1008.0,304.09,301.75,7.07
4,659e617af63ecd73f81c104e,303.04,303.04,1704842362,2024-01-10 09:16:36,1704884028,overcast clouds,66.0,Rach Gia,1008.0,307.01,303.04,2.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3211,65a8eb21c54c1129e3d41bbf,297.63,297.63,1705534871,2024-01-18 09:10:57,1705574380,overcast clouds,72.0,Yen Bai,1011.0,298.01,297.63,1.27
3212,65a8eb7bc54c1129e3d41bc0,297.47,297.47,1705534800,2024-01-18 09:12:27,1705574283,overcast clouds,71.0,Tuyen Quang,1011.0,297.81,297.47,1.59
3213,65a8ebd6c54c1129e3d41bc1,299.03,299.03,1705534625,2024-01-18 09:13:58,1705574157,overcast clouds,67.0,Thai Nguyen,1011.0,299.42,299.03,3.41
3214,65a8ec30c54c1129e3d41bc2,294.35,294.35,1705534684,2024-01-18 09:15:28,1705574103,overcast clouds,90.0,Bac Kan,1012.0,294.88,294.35,0.64
3215,65a8ec8ac54c1129e3d41bc3,302.09,302.09,1705533582,2024-01-18 09:16:58,1705575533,overcast clouds,59.0,Ca Mau,1007.0,303.93,302.09,3.40

In [4]:
#  drop the _id, report_time, descripton columns
Vie_weather = Vie_weather.drop(columns=['_id', 'report_time'])
Vie_weather

,temp,temp_min,sunrise,sunset,description,humidity,location,pressure,feels_like,temp_max,wind
0,305.12,305.12,1704842319,1704883911,overcast clouds,52.0,Long Xuyen,1007.0,307.95,305.12,1.51
1,303.11,303.11,1704842106,1704883854,overcast clouds,56.0,Soc Trang,1008.0,305.15,303.11,5.68
2,304.11,304.11,1704842263,1704884095,overcast clouds,53.0,Ca Mau,1008.0,306.31,304.11,5.06
3,301.75,301.75,1704842135,1704883947,overcast clouds,64.0,Bac Lieu,1008.0,304.09,301.75,7.07
4,303.04,303.04,1704842362,1704884028,overcast clouds,66.0,Rach Gia,1008.0,307.01,303.04,2.05
...,...,...,...,...,...,...,...,...,...,...,...
3211,297.63,297.63,1705534871,1705574380,overcast clouds,72.0,Yen Bai,1011.0,298.01,297.63,1.27
3212,297.47,297.47,1705534800,1705574283,overcast clouds,71.0,Tuyen Quang,1011.0,297.81,297.47,1.59
3213,299.03,299.03,1705534625,1705574157,overcast clouds,67.0,Thai Nguyen,1011.0,299.42,299.03,3.41
3214,294.35,294.35,1705534684,1705574103,overcast clouds,90.0,Bac Kan,1012.0,294.88,294.35,0.64
3215,302.09,302.09,1705533582,1705575533,overcast clouds,59.0,Ca Mau,1007.0,303.93,302.09,3.40

In [5]:
Vie_weather.columns

Index(['temp', 'temp_min', 'sunrise', 'sunset', 'description', 'humidity',
       'location', 'pressure', 'feels_like', 'temp_max', 'wind'],
      dtype='object')

In [6]:
# info about the data
Vie_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3216 entries, 0 to 3215
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   temp         3216 non-null   float64
 1   temp_min     3216 non-null   float64
 2   sunrise      3216 non-null   int64
 3   sunset       3216 non-null   int64
 4   description  3216 non-null   object
 5   humidity     3216 non-null   float64
 6   location     3216 non-null   object
 7   pressure     3216 non-null   float64
 8   feels_like   3216 non-null   float64
 9   temp_max     3216 non-null   float64
 10  wind         3216 non-null   float64
dtypes: float64(7), int64(2), object(2)
memory usage: 276.5+ KB

In [7]:
# count unique values in location columns 
locations = Vie_weather['location'].value_counts()
print(locations.index)

Index(['Ca Mau', 'Loc Ninh', 'Pleiku', 'Phan Thiet', 'Phu Khuong', 'Da Lat',
       'Buon Ma Thuot', 'Phan Rang-Thap Cham', 'Nha Trang', 'Kon Tum',
       'Vung Tau', 'Tuy Hoa', 'Quy Nhon', 'Turan', 'Quang Ngai', 'Bac Lieu',
       'Bien Hoa', 'Long Xuyen', 'Soc Trang', 'Kwang Binh', 'Ha Tinh', 'Vinh',
       'Thanh Hoa', 'Ninh Binh', 'Nam Dinh', 'Thai Binh', 'Phu Ly', 'Hung Yen',
       'Hai Duong', 'Quang Tri', 'Hue', 'Hoi An', 'Ho Chi Minh City', 'Tan An',
       'My Tho', 'Tra Vinh', 'Ben Tre', 'Cao Lanh', 'Vinh Long', 'Can Tho',
       'Rach Gia', 'Thu Dau Mot', 'Cao Bang', 'Lao Cai', 'Ha Giang',
       'Lang Son', 'Ha Long', 'Haiphong', 'Lai Chau', 'Son La',
       'Dien Bien Phu', 'Ha Noi', 'Hoa Binh', 'Viet Tri', 'Vinh Yen',
       'Bac Giang', 'Bac Ninh', 'Yen Bai', 'Tuyen Quang', 'Thai Nguyen',
       'Bac Kan'],
      dtype='object', name='location')

In [8]:
city_province_mapping = {
    'Lang Son': 'Lang Son',
    'Hue': 'Thua Thien - Hue',
    'Kon Tum': 'Kon Tum',
    'Kwang Binh': 'Quang Binh',
    'Lao Cai': 'Lao Cai',
    'Loc Ninh': 'Binh Phuoc',
    'Nam Dinh': 'Nam Dinh',
    'Nha Trang': 'Khanh Hoa',
    'Ninh Binh': 'Ninh Binh',
    'Phan Rang-Thap Cham': 'Ninh Thuan',
    'Phan Thiet': 'Binh Thuan',
    'Phu Khuong': 'Tay Ninh',
    'Phu Ly': 'Ha Nam',
    'Pleiku': 'Gia Lai',
    'Quang Ngai': 'Quang Ngai',
    'Quang Tri': 'Quang Tri',
    'Quy Nhon': 'Binh Dinh',
    'Thai Binh': 'Thai Binh',
    'Thanh Hoa': 'Thanh Hoa',
    'Turan': 'Da Nang',
    'Tuy Hoa': 'Phu Yen',
    'Hung Yen': 'Hung Yen',
    'Vinh': 'Nghe An',
    'Hoi An': 'Quang Nam',
    'Ha Long': 'Quang Ninh',
    'Bac Lieu': 'Bac Lieu',
    'Vung Tau': 'Ba Ria-Vung Tau',
    'Bien Hoa': 'Dong Nai',
    'Buon Ma Thuot': 'Dak Lak',
    'Ca Mau': 'Ca Mau',
    'Da Lat': 'Lam Dong',
    'Ha Giang': 'Ha Giang',
    'Cao Bang': 'Cao Bang',
    'Hai Duong': 'Hai Duong',
    'Haiphong': 'Hai Phong',
    'Ha Tinh': 'Ha Tinh',
    'Ha Noi': 'Ha Noi',
    'Tan An': 'Long An',
    'Ho Chi Minh City': 'Ho Chi Minh city',
    'Lai Chau': 'Lai Chau',
    'Tra Vinh': 'Tra Vinh',
    'Thu Dau Mot': 'Binh Duong',
    'Ben Tre': 'Ben Tre',
    'Vinh Long': 'Vinh Long',
    'Viet Tri': 'Phu Tho',
    'Soc Trang': 'Soc Trang',
    'Son La': 'Son La',
    'Rach Gia': 'Kien Giang',
    'Can Tho': 'Can Tho',
    'Hoa Binh': 'Hoa Binh',
    'Cao Lanh': 'Dong Thap',
    'Vinh Yen': 'Vinh Phuc',
    'Dien Bien Phu': 'Dien Bien',
    'My Tho': 'Tien Giang',
    'Long Xuyen': 'An Giang',
    'Bac Giang': 'Bac Giang',
    'Bac Ninh': 'Bac Ninh',
    'Yen Bai': 'Yen Bai',
    'Tuyen Quang': 'Tuyen Quang',
    'Thai Nguyen': 'Thai Nguyen',
    'Bac Kan': 'Bac Kan'
}

# Replace the city names with corresponding provinces
Vie_weather['province'] = Vie_weather['location'].replace(city_province_mapping)
# drop location column 
Vie_weather.drop(columns=['location'], inplace=True)

In [9]:
# sort by location 
Vie_weather = Vie_weather.sort_values(by='province')
Vie_weather

,temp,temp_min,sunrise,sunset,description,humidity,pressure,feels_like,temp_max,wind,province
0,305.12,305.12,1704842319,1704883911,overcast clouds,52.0,1007.0,307.95,305.12,1.51,An Giang
342,303.12,303.12,1704928736,1704970342,few clouds,57.0,1009.0,305.35,303.12,1.65,An Giang
2853,297.12,297.12,1705533630,1705575357,overcast clouds,86.0,1012.0,297.82,297.12,0.57,An Giang
1755,297.12,297.12,1705447219,1705488927,overcast clouds,86.0,1010.0,297.82,297.12,1.71,An Giang
1694,297.12,297.12,1705447219,1705488927,overcast clouds,84.0,1011.0,297.77,297.12,2.16,An Giang
...,...,...,...,...,...,...,...,...,...,...,...
105,291.47,291.47,1704843642,1704882852,overcast clouds,94.0,1017.0,291.81,291.47,0.93,Yen Bai
2906,292.97,292.97,1705534871,1705574380,overcast clouds,95.0,1017.0,293.49,292.97,1.52,Yen Bai
2479,293.63,293.63,1705448472,1705487939,overcast clouds,91.0,1016.0,294.11,293.63,1.70,Yen Bai
2723,292.85,292.85,1705534871,1705574380,overcast clouds,96.0,1014.0,293.38,292.85,0.99,Yen Bai
1564,292.07,292.07,1705362072,1705401497,overcast clouds,94.0,1019.0,292.47,292.07,0.25,Yen Bai

In [10]:
provinces = Vie_weather['province'].value_counts().sort_index()
print(provinces.index)
print("Provinces values : \n", provinces.values)
# count number of index in provinces
print("Number of provinces : ", len(provinces.index))

Index(['An Giang', 'Ba Ria-Vung Tau', 'Bac Giang', 'Bac Kan', 'Bac Lieu',
       'Bac Ninh', 'Ben Tre', 'Binh Dinh', 'Binh Duong', 'Binh Phuoc',
       'Binh Thuan', 'Ca Mau', 'Can Tho', 'Cao Bang', 'Da Nang', 'Dak Lak',
       'Dien Bien', 'Dong Nai', 'Dong Thap', 'Gia Lai', 'Ha Giang', 'Ha Nam',
       'Ha Noi', 'Ha Tinh', 'Hai Duong', 'Hai Phong', 'Ho Chi Minh city',
       'Hoa Binh', 'Hung Yen', 'Khanh Hoa', 'Kien Giang', 'Kon Tum',
       'Lai Chau', 'Lam Dong', 'Lang Son', 'Lao Cai', 'Long An', 'Nam Dinh',
       'Nghe An', 'Ninh Binh', 'Ninh Thuan', 'Phu Tho', 'Phu Yen',
       'Quang Binh', 'Quang Nam', 'Quang Ngai', 'Quang Ninh', 'Quang Tri',
       'Soc Trang', 'Son La', 'Tay Ninh', 'Thai Binh', 'Thai Nguyen',
       'Thanh Hoa', 'Thua Thien - Hue', 'Tien Giang', 'Tra Vinh',
       'Tuyen Quang', 'Vinh Long', 'Vinh Phuc', 'Yen Bai'],
      dtype='object', name='province')
Provinces values :
 [53 54 51 50 54 51 53 54 53 54 54 55 53 52 54 54 51 54 53 54 52 53 51 53
 53 52 53 51 53 54 53 54 51 54 52 52 53 53 53 53 54 51 54 53 53 54 52 53
 53 51 54 53 50 53 53 53 53 50 53 51 51]
Number of provinces :  61

## missing provinces: Hau Giang Dak nong 
--> fill the Tay Ninh data by Binh Phuoc and 
#### 
--> Hau Giang by Can Tho (Since they are neighbors--> same weather)

In [11]:
# Index values for 'Lam Dong' and 'Quang Nam'
Hau_Giang = Vie_weather[Vie_weather['province'] == 'Can Tho'].index
Dak_Nong = Vie_weather[Vie_weather['province'] == 'Dak Lak'].index

In [12]:
Vie_weather = pd.concat([Vie_weather, Vie_weather.loc[Hau_Giang].replace({'province': 'Can Tho'}, 'Hau Giang')], ignore_index=True)

In [13]:
Vie_weather = pd.concat([Vie_weather, Vie_weather.loc[Dak_Nong].replace({'province': 'Dak Lak'}, 'Dak Nong')], ignore_index=True)

In [14]:
province = Vie_weather['province'].value_counts().sort_index()
print(province.index)
print("Provinces values : \n", province.values)
# count number of index in provinces
print("Number of provinces : ", len(province.index))

Index(['An Giang', 'Ba Ria-Vung Tau', 'Bac Giang', 'Bac Kan', 'Bac Lieu',
       'Bac Ninh', 'Ben Tre', 'Binh Dinh', 'Binh Duong', 'Binh Phuoc',
       'Binh Thuan', 'Ca Mau', 'Can Tho', 'Cao Bang', 'Da Nang', 'Dak Lak',
       'Dak Nong', 'Dien Bien', 'Dong Nai', 'Dong Thap', 'Gia Lai', 'Ha Giang',
       'Ha Nam', 'Ha Noi', 'Ha Tinh', 'Hai Duong', 'Hai Phong', 'Hau Giang',
       'Ho Chi Minh city', 'Hoa Binh', 'Hung Yen', 'Khanh Hoa', 'Kien Giang',
       'Kon Tum', 'Lai Chau', 'Lam Dong', 'Lang Son', 'Lao Cai', 'Long An',
       'Nam Dinh', 'Nghe An', 'Ninh Binh', 'Ninh Thuan', 'Phu Tho', 'Phu Yen',
       'Quang Binh', 'Quang Nam', 'Quang Ngai', 'Quang Ninh', 'Quang Tri',
       'Soc Trang', 'Son La', 'Tay Ninh', 'Thai Binh', 'Thai Nguyen',
       'Thanh Hoa', 'Thua Thien - Hue', 'Tien Giang', 'Tra Vinh',
       'Tuyen Quang', 'Vinh Long', 'Vinh Phuc', 'Yen Bai'],
      dtype='object', name='province')
Provinces values :
 [54 55 52 51 55 52 54 55 53 55 55 56 54 53 55 54  1 51 56 53 55 54 54 51
 54 54 53 53 54 52 54 54 54 55 52 55 53 53 54 53 54 54 55 52 55 54 53 55
 53 54 54 52 55 54 50 54 54 54 54 51 54 51 52]
Number of provinces :  63

#### In the economic and deforestation datasets, we have collected historical data spanning seven years for various provinces and municipalities. Therefore, we will randomly select seven columns to make predictions on the "Tropical Forest Loss per Hectare" column.

In [15]:
target_count = 7

# Create an empty DataFrame to store the filtered data
filtered_data = pd.DataFrame()

# Iterate over unique provinces
for province in Vie_weather['province'].unique():
    # Get rows for the current province
    province_rows = Vie_weather[Vie_weather['province'] == province].copy()
    
    # If there are more than 7 rows, randomly select 7 rows
    if len(province_rows) > target_count:
        province_rows = province_rows.sample(n=target_count, random_state=42)
    
    # If there are fewer than 7 rows, duplicate existing rows until reaching 7
    while len(province_rows) < target_count:
        province_rows = pd.concat([province_rows, province_rows.sample(n=target_count - len(province_rows), replace=True, random_state=42)])
    
    # Append the processed rows to the filtered data
    filtered_data = pd.concat([filtered_data, province_rows])

# Reset index of the filtered data
filtered_data.reset_index(drop=True, inplace=True)
Vie_weather = filtered_data
Vie_weather

,temp,temp_min,sunrise,sunset,description,humidity,pressure,feels_like,temp_max,wind,province
0,298.12,298.12,1705447219,1705488927,scattered clouds,77.0,1013.0,298.68,298.12,2.47,An Giang
1,295.80,295.80,1705015152,1705056774,broken clouds,86.0,1011.0,296.37,295.80,2.66,An Giang
2,303.12,303.12,1705360808,1705402497,broken clouds,49.0,1011.0,304.00,303.12,1.97,An Giang
3,302.12,302.12,1705533630,1705575357,broken clouds,62.0,1013.0,304.44,302.12,2.46,An Giang
4,297.12,297.12,1705015152,1705056774,overcast clouds,90.0,1011.0,297.92,297.12,1.77,An Giang
...,...,...,...,...,...,...,...,...,...,...,...
436,300.82,300.82,1705360395,1705401646,overcast clouds,47.0,1012.0,301.01,300.82,5.05,Dak Nong
437,300.82,300.82,1705360395,1705401646,overcast clouds,47.0,1012.0,301.01,300.82,5.05,Dak Nong
438,300.82,300.82,1705360395,1705401646,overcast clouds,47.0,1012.0,301.01,300.82,5.05,Dak Nong
439,300.82,300.82,1705360395,1705401646,overcast clouds,47.0,1012.0,301.01,300.82,5.05,Dak Nong
440,300.82,300.82,1705360395,1705401646,overcast clouds,47.0,1012.0,301.01,300.82,5.05,Dak Nong

In [16]:
# sort index by province
Vie_weather = Vie_weather.sort_values(by='province')
Vie_weather

,temp,temp_min,sunrise,sunset,description,humidity,pressure,feels_like,temp_max,wind,province
0,298.12,298.12,1705447219,1705488927,scattered clouds,77.0,1013.0,298.68,298.12,2.47,An Giang
1,295.80,295.80,1705015152,1705056774,broken clouds,86.0,1011.0,296.37,295.80,2.66,An Giang
2,303.12,303.12,1705360808,1705402497,broken clouds,49.0,1011.0,304.00,303.12,1.97,An Giang
3,302.12,302.12,1705533630,1705575357,broken clouds,62.0,1013.0,304.44,302.12,2.46,An Giang
4,297.12,297.12,1705015152,1705056774,overcast clouds,90.0,1011.0,297.92,297.12,1.77,An Giang
...,...,...,...,...,...,...,...,...,...,...,...
426,290.92,290.92,1705016457,1705055733,overcast clouds,97.0,1017.0,291.29,290.92,0.62,Yen Bai
425,292.90,292.90,1705534871,1705574380,overcast clouds,95.0,1015.0,293.41,292.90,1.09,Yen Bai
424,296.89,296.89,1705448472,1705487939,overcast clouds,69.0,1015.0,297.12,296.89,1.65,Yen Bai
422,292.97,292.97,1705534871,1705574380,overcast clouds,95.0,1017.0,293.49,292.97,1.52,Yen Bai
423,291.02,291.02,1704930050,1704969292,overcast clouds,97.0,1017.0,291.40,291.02,0.72,Yen Bai

In [17]:
# save the data to excel
Vie_weather.to_excel('../data/processed/Vie_weather.xlsx', index=False)

In [18]:
database_username = "admin01"
database_password = "LZRKfNnjX38rCOMs"
database_cluster_name = "bigdataforengineering.wef2a2d.mongodb.net"
connection_string = f"mongodb+srv://{database_username}:{database_password}@{database_cluster_name}/?retryWrites=true&w=majority"

new_database = 'processed_data'
open_weather = 'vie_weather'

# Connect to MongoDB
client = pymongo.MongoClient(connection_string)

# Check if the connection was successful
if client.server_info():
    print("Connected to MongoDB successfully!")

Connected to MongoDB successfully!

In [19]:
# Access the specified database and collection
db = client[new_database]
collection = db[open_weather]

if open_weather in db.list_collection_names():
    # Collection exists, so drop it
    db[open_weather].drop()
    print(f"Dropped collection {open_weather}")
else:
    print(f"Collection {open_weather} does not exist")

Dropped collection vie_weather

In [20]:
# Read the Excel file into a DataFrame
Vie_weather = pd.read_excel('../data/processed/Vie_weather.xlsx')
# Save the DataFrame to MongoDB
collection.insert_many(Vie_weather.to_dict('records'))

# Verify if the data has been successfully inserted
cursor = collection.find({})
data_list = list(cursor)
updated_data = pd.DataFrame(data_list)
print("Data successfully inserted into MongoDB collection:", open_weather)

# Close the MongoDB connection
client.close()

Data successfully inserted into MongoDB collection: vie_weather